### ISSUE TITLE
Clicking some TOC entries gives "not found" error.

### ISSUE THREAD

**Issue by bulrush15** [bubble-Q/QiuReader#17]
When I click on the third table of contents entry "Shambala" (with red square in image) I get a "file not found" from your EPUB reader. But when I use cursor right to go to the next chapter, it works. 

Please make sure that when you make TOC entries, that they are unique. I made a program to make EPUB files and I appended a 5 digit sequential number to each header id, like 00001, 00002, so header ids in this epub should look like \#shambhala00001, \#shambhala00002, etc. There is always a chance that the headers will be the exact same text like in this example.

Steps to reproduce: 

1. Unzip the attached zip file which will give you an epub file.
2. Open Firefox and use QiuReader to open the EPUB file. 
3. Click on the third TOC entry called "SHAMBHALA". See image. You should get an error.

[shambhala.zip](https://github.com/bubble-Q/QiuReader/files/1991404/shambhala.zip)

![shamb-toc](https://user-images.githubusercontent.com/7031486/39867247-004e1dc0-5422-11e8-8a7c-a1afd2dd66e9.png)

**Comment by huangjj27** [comment]
I encounter the exactly same issue！

**Comment by bubble-Q** [comment]
Thank you, I have successfully reproduced this problem. It has been fixed. @bulrush15
