### ISSUE TITLE
选中文字弹出标注的 feature 会导致 ctrl+c 快捷键失效

### ISSUE THREAD

**Issue by Engiun** [bubble-Q/QiuReader#6]
发现最好看的一个 firefox 阅读 epub 扩展了，
能不能做一个兼容呢？选中文字的时候既弹出标注又不会屏蔽快捷键。
> 另外希望能自定义字距，西文的字距并不适用中文，把中文字距增大更适合大量文字的阅读

**Comment by bubble-Q** [comment]
@Engiun 谢谢反馈。我在 Firefox 56.0 开发者版(64 bit)上测试了下，发现可以使用 Ctrl + C 进行文字复制，不过不能使用弹出菜单的 Copy 选项进行复制，能告诉我你的 Firefox 版本吗？我会尝试尽快修复这个问题的。

另外：中文文档改变字间距可以使用 **Setting -> spacing -> Letter spacing** 来完成。

**Comment by Engiun** [comment]
@bubble-Q 我是 firefox 53 没开多进程，不过我在最新的 nighty 64 位（完全空白配置，没有脚本和样式的干扰）上也装了这个扩展，也是同样的问题呢，直接选中就 ctrl+c 的话，并不能复制文字（使用弹出菜单的 copy 也不行）。看看你那边能不能重现呢？
ps. 字距那个问题，我眼神不好，居然没有发现右下角的浮动工具栏 -_-! 现在搞定了，谢谢

**Comment by Engiun** [comment]
@bubble-Q  发现这个扩展对标注汉字读音的<ruby>标签的支持也非常好，
对注释的处理也比别的扩展强，目前是点击注释的锚点链接跳转到注释区，再点击注释区的链接跳转回正文，但是我觉得还是有点麻烦了，
可以不以做成弹出注释呢，就是鼠标放到注释的数字上标那里不点击，自动加载注释区的内容到一个弹出窗口，想看得更仔细的，再点击那个上标跳转。仅仅是建议~

**Comment by bubble-Q** [comment]
@Engiun 感谢帮忙测试 ^O^ 。测试之后我也发现这个问题了，是个需要解决的问题，目前正在修改中。

另外，由于书籍的解析是由 [epub.js](https://github.com/futurepress/epub.js) 这个库完成的，对于你提出的建议我目前没有能力实现，不过还是很感谢你的建议。如果使用过程中有什么其他问题的话，欢迎提出，我会尽力解决的~

**Comment by bubble-Q** [comment]
@Engiun 问题已修复

**Comment by Engiun** [comment]
@bubble-Q 谢谢，确实好了，
另外又发现了一个关于`<ruby>`标签的问题，就不另外开话题了
在默认的分页浏览模式（setting ->page  -> 左边那个选项）下，有 ruby 的那行的行距会比没有 ruby 的大，但是如果那行处于一个分页的第一行， ruby 会显示不全
![qq 20170823091413](https://user-images.githubusercontent.com/4875907/29594454-830b0784-87e3-11e7-845b-38cb4f6cd7a7.png)
这个是 epub.js 的问题吗？可以调整下么

**Comment by bubble-Q** [comment]
关于有 `<ruby>` 标签的行行距增大，我认为应该是浏览器渲染的正常行为（目前没找到材料来测试）。而 处于第一行的 `<ruby>` 标签显示不全，可能是 epub.js 自动分页的锅（真不是我甩锅 ╮(╯▽╰)╭）。后面我会测试一下。

**Comment by Engiun** [comment]
@bubble-Q  那行行距增大是应该的，我表达的是赞美！“但是”后面才是我反馈的问题本体...
我也猜到是 epub.js 的问题 ╮(╯▽╰)╭，想直接去那个项目下面反馈，英文不好好苦恼╮(╯▽╰)╭
总之谢谢，辛苦了

**Comment by bubble-Q** [comment]
@Engiun 谢谢夸奖😊
